# Generated by Django 4.1.5 on 2023-05-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=70)),
                ('publisher', models.CharField(max_length=70)),
                ('publish_date', models.DateField()),
                ('category', models.CharField(max_length=70)),
            ],
        ),
    ]
